### ISSUE TITLE
Following the README.md, the first time to write the doc '_design/mailbox' will get an error

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-package-cloudant#110]
Following the document README.md to create a filter, when I type `wsk action invoke /_/myCloudant/write -p dbname testdb -p overwrite true -P design_doc.json -r` and return, I will get an error:
```
"Error: missing\n    at Request._callback (/nodejsAction/node_modules/cloudant-nano/lib/nano.js:247:15)\n    at Request.self.callback (/nodejsAction/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/nodejsAction/node_modules/request/request.js:1081:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/nodejsAction/node_modules/request/request.js:1001:12)\n    at IncomingMessage.g (events.js:291:16)",
```

I think here we should remove `-p overwrite true` since it's the first time to create the doc. README.md should be updated.

**Comment by daisy-ycguo** [comment]
The root cause is #112.

There can be two possible solutions (1) change the source code as suggested in #112. (2) change the document.

**Comment by tleyden** [comment]
@daisy-ycguo I think the code would need to be changed.  When you say change the document, what do you have in mind?
