### ISSUE TITLE
Exclude views and design documents from when querying for trigger documents

### ISSUE THREAD

**Issue by jeremiaswerner** [apache/incubator-openwhisk-package-cloudant#71]
Creation of a design document caused the trigger service to crash because the design document is interpreted as a trigger definition. 

```
/cloudantTrigger/lib/utils.js:66
            dbHost = dbHost.replace('https://','');
                           ^

TypeError: Cannot read property 'replace' of undefined
    at createTrigger (/cloudantTrigger/lib/utils.js:66:25)
    at /cloudantTrigger/lib/utils.js:230:28
    at Array.forEach (native)
    at /cloudantTrigger/lib/utils.js:218:27
    at Request._callback (/cloudantTrigger/node_modules/nano/lib/nano.js:217:16)
    at Request.self.callback (/cloudantTrigger/node_modules/request/request.js:199:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/cloudantTrigger/node_modules/request/request.js:1036:10)
    at emitOne (events.js:101:20)
```

**Comment by jasonpet** [comment]
How did a design document get into the trigger database?  I don't see how this can occur unless someone manually did this.  They must have restarted the container as well otherwise it would not have tried to create a trigger from the entry.  See a few problems here:
1.  Should have created view on environment other than yp first
2.  Should have let people know (me for one) what was being done and that provider would be restarted.
